#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        iif lo accept
        ct state established,related accept
        tcp dport 22 accept
        ip saddr 192.168.22.254 tcp dport 8000 accept
        icmp type echo-request accept
        icmpv6 type echo-request accept
        log prefix "NFT-DROP: " flags all counter drop
    }

    chain forward {
        type filter hook forward priority filter; policy drop
    }

    chain output {
        type filter hook output priority filter; policy accept
    }
}
